import {PageSchema} from "@/components/constructor/page-render/types";

const schema: PageSchema = {
    meta: {
        title: "MakeMyCV — Professional & AI-Powered Resume Creation",
        description:
            "Get a professionally crafted CV made by experts or instantly generate one using AI. High-quality, ATS-friendly, and tailored for your dream job.",
        keywords: [
            "create cv",
            "professional resume",
            "ai cv",
            "cv specialist",
            "make my cv",
            "resume builder",
        ],
        canonical: "/",
    },

    blocks: [
        // 🟣 HERO
        {
            type: "custom",
            component: "HeroSection",
            title: "Get a Job-Winning CV",
            highlight: "Made by Experts or Powered by AI",
            description:
                "Two ways to build your perfect CV: crafted manually by a professional (ready in 24h), or instantly generated by AI. Choose your method and start your career boost today.",
            primaryCta: {text: "Order Professional CV", link: "/dashboard"},
            secondaryCta: {text: "Generate AI CV", link: "/dashboard"},
            image: "image1",
            showTrustBadge: true,
        },

        // 🟦 INFOBLOCK — два методи
        {
            type: "section",
            title: "Choose How You Want to Create Your CV",
            description: "Select the method that fits your time, needs, and career goals.",
            left: {
                type: "custom",
                component: "InfoBlock",
                title: "CV Created by a Specialist",
                description:
                    "Your CV is crafted manually by a professional writer. Detailed, polished, and ready to impress recruiters.",
                bullets: [
                    "Delivered in 24 hours",
                    "Rewrite of experience & achievements",
                    "ATS-friendly formatting",
                    "Ideal for important job applications",
                ],
                image: "image2",
                align: "left",
                imageHeight: "360px",

            },
            right: {
                type: "custom",
                component: "InfoBlock",
                title: "AI Instant CV Generator",
                description:
                    "Generate a complete CV instantly using advanced AI trained on thousands of successful resumes.",
                bullets: [
                    "Instant generation",
                    "AI rewrite of work experience",
                    "Clean & modern design",
                    "Affordable and fast",
                ],
                image: "image3",
                align: "left",
                imageHeight: "360px",
            },
        },

        // 🟣 HIGHLIGHT STRIP
        {
            type: "custom",
            component: "HighlightStrip",
            items: [
                {icon: "🚀", text: "Fast Delivery", subtext: "Instant or 24h"},
                {icon: "📄", text: "PDF & DOCX", subtext: "Professional formats"},
                {icon: "🤖", text: "AI Rewrite", subtext: "Smart + clean text"},
                {icon: "🎯", text: "ATS Friendly", subtext: "Optimized for HR filters"},
                {icon: "🎨", text: "Modern Templates", subtext: "Designed to impress"},
                {icon: "🧩", text: "Custom Options", subtext: "Extras for any CV"},
            ],
        },
        {
            type: "custom",
            component: "SideSliderShowcase",

            slides: [
                {
                    image: "image4",
                    title: "Cover Letter",
                    description: "A tailored, professionally written cover letter that highlights your strengths and matches the job description."
                },
                {
                    image: "image5",
                    title: "LinkedIn Section",
                    description: "Optimized LinkedIn About + Experience text designed to increase profile visibility and recruiter engagement."
                },
                {
                    image: "image7",
                    title: "Keyword Boost",
                    description: "Adds job-specific keywords to improve ATS ranking and match employer search criteria."
                },
                {
                    image: "image8",
                    title: "ATS Report",
                    description: "A detailed scan showing compatibility with Applicant Tracking Systems and recommendations for improvement."
                },
                {
                    image: "image9",
                    title: "Job Adaptation",
                    description: "Fully adapts your CV to a specific job posting for maximum relevance and higher interview chances."
                },
                {
                    image: "image10",
                    title: "Achievements",
                    description: "Transforms responsibilities into measurable achievements using STAR/quantification methods."
                },
                {
                    image: "image11",
                    title: "Skills Gap",
                    description: "Analyzes your CV and highlights missing skills with suggestions to strengthen your professional profile."
                },
                {
                    image: "image12",
                    title: "Custom Color",
                    description: "Applies a personalized color style to your CV while keeping it clean, modern, and ATS-friendly."
                },
            ],

            height: "420px"
        },

        // 🟡 TIMELINE — процес для Manual
        {
            type: "custom",
            component: "Timeline",
            title: "How the Professional CV Creation Works",
            steps: [
                {
                    title: "1. Share Your Details",
                    description: "Provide your experience, skills, goals, and job preferences.",
                },
                {
                    title: "2. CV Analysis",
                    description: "Your information is reviewed by a CV specialist.",
                },
                {
                    title: "3. Professional Rewriting",
                    description: "Achievements and responsibilities are rewritten for impact.",
                },
                {
                    title: "4. Modern Formatting",
                    description: "Your CV is structured and designed for ATS compatibility.",
                },
                {
                    title: "5. Final Review",
                    description: "A human expert checks clarity, grammar, and style.",
                },
                {
                    title: "6. Delivery in 24h",
                    description: "You receive your polished CV in PDF and DOCX.",
                },
            ],
        },

        {
            type: "custom",
            component: "ExamplesGrid",
            title: "Choose Your CV Style",
            description: "Below are premium CV templates designed to stand out and pass HR filters."
        },


        {
            type: "section",
            title: "How It Works In Actions",
            description:
                "See how our formatting and design enhance the CV's professionalism and readability.",
            gap: "2rem",
            left: {
                type: "custom",
                title: "How Specialist-Made CV Looks",
                description: "Step-by-step transformation of CV compiled by our expert.",

                align: "left",
                textGap: "0rem",
                mediaGap: "0.5rem",
                titleSize: "1.5rem",
                descriptionSize: "1rem",

                component: "VideoDemo",
                video: "demo",
            },
            right: {
                type: "custom",
                title: "AI CV Generation Process",
                description: "AI CV generation process from input to final output.",

                align: "right",
                textGap: "0rem",
                mediaGap: "0.5rem",
                titleSize: "1.5rem",
                descriptionSize: "1rem",

                component: "VideoDemo",
                video: "demoAi",
            },
        },


        // 🧩 EXTRAS SECTION
        {
            type: "section",
            title: "Enhance Your CV with Professional Extras",
            description:
                "Add more value to your order with optional improvements written by a specialist.",
            left: {
                type: "grid",
                columns: 3,
                gap: "1.3rem",
                items: [
                    {
                        key: "extra1",
                        block: {
                            type: "card",
                            image: "image13",
                            title: "Cover Letter",
                            description:
                                "A personalised cover letter that increases your interview chances.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                    {
                        key: "extra2",
                        block: {
                            type: "card",
                            image: "image14",
                            title: "LinkedIn Rewrite",
                            description:
                                "Professional rewriting of your LinkedIn About & Experience.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                    {
                        key: "extra3",
                        block: {
                            type: "card",
                            image: "image15",
                            title: "ATS Check",
                            description:
                                "Test your CV for Applicant Tracking Systems and fix issues.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                    {
                        key: "extra4",
                        block: {
                            type: "card",
                            image: "image16",
                            title: "Job Adaptation",
                            description:
                                "Tailoring your CV to a specific job description.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                    {
                        key: "extra5",
                        block: {
                            type: "card",
                            image: "image17",
                            title: "Achievement Enhancement",
                            description:
                                "Transform responsibilities into measurable achievements.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                    {
                        key: "extra6",
                        block: {
                            type: "card",
                            image: "image18",
                            title: "Skills Gap Analysis",
                            description:
                                "Identify and fill skill gaps in your CV.",
                            buttonText: "Add to CV",
                            buttonLink: "/dashboard",
                        },
                    },
                ],
            },
        },

        // ⭐ TESTIMONIALS
        {
            type: "custom",
            component: "TestimonialsSlider",
            title: "What Our Users Say",
            description: "Real feedback from job seekers who used MakeMyCV to upgrade their resumes and get more interviews.",
            testimonials: [
                {
                    name: "Alexander",
                    role: "Software Engineer",
                    image: "review9",
                    text: "MakeMyCV completely transformed my outdated CV. Recruiters finally started replying — got an interview in 3 days.",
                },
                {
                    name: "John",
                    role: "Business Analyst",
                    image: "review10",
                    text: "The AI-rewritten experience section looks cleaner and more professional than anything I’ve ever done manually.",
                },
                {
                    name: "Olena",
                    role: "UI/UX Designer",
                    image: "review12",
                    text: "The CV design looks premium and modern. HRs even complimented the structure during the interview.",
                },
                {
                    name: "Janet",
                    role: "Project Manager",
                    image: "review13",
                    text: "The generator fixed all my wording issues. Clear, structured, and tailored exactly to my role.",
                },
                {
                    name: "Samuel",
                    role: "QA Engineer",
                    image: "review11",
                    text: "Didn’t expect AI to write such strong bullet points. My CV finally looks senior-level.",
                },
            ],
        },

        {
            type: "grid",
            columns: 4,
            gap: "2rem",
            cards: [
                {
                    type: "pricing",
                    variant: "starter",
                    title: "Professional CV Creation",
                    price: "€10",
                    tokens: 1000,
                    badgeTop: "For Serious Applicants",
                    description: "Hand-crafted CV made by a specialist in 24 hours.",
                    features: [
                        "Human-crafted writing",
                        "ATS-friendly formatting",
                        "Modern layout",
                        "Delivered in PDF & DOCX",
                    ],
                    buttonText: "Order Now",
                },
                {
                    type: "pricing",
                    variant: "pro",
                    title: "AI CV Generator",
                    price: "€25",
                    tokens: 2500,
                    badgeTop: "Fast & Affordable",
                    description: "Instant AI-generated CV with rewriting and clean design.",
                    features: [
                        "Instant PDF/DOCX export",
                        "AI bullet rewrite",
                        "Modern design",
                        "Optimized structure",
                    ],
                    buttonText: "Order Now",

                },
                {
                    type: "pricing",
                    variant: "premium",
                    title: "Cover Letter",
                    price: "€50",
                    tokens: 5000,
                    badgeTop: "Most Popular Add-on",
                    description:
                        "A personalised cover letter that improves recruiter response rates.",
                    features: [
                        "Tailored for your role",
                        "ATS-friendly",
                        "Professional tone",
                    ],
                    buttonText: "Order Now",

                },

                // ⭐ CUSTOM PACKAGE — ПОВНІСТЮ ВИГЛЯДАЄ ЯК ДИНАМІЧНИЙ ОПЦІОН
                {
                    type: "pricing",
                    variant: "custom",
                    title: "Custom Package",
                    price: "dynamic",
                    tokens: 0,
                    badgeTop: "Flexible Option",
                    description:
                        "Choose any combination of services and pay only for what you need.",
                    features: [
                        "Mix & match extras",
                        "Flexible pricing",
                        "Perfect for complex CV needs",
                    ],
                    buttonText: "Order Now",

                },
            ],
        },


        // ❓ FAQ
        {
            type: "faq",
            items: [
                {
                    question: "How long does the specialist take?",
                    answer: "You will receive your CV within 24 hours.",
                },
                {
                    question: "Does AI CV look professional?",
                    answer:
                        "Yes, AI rewrites your bullet points and formats everything automatically.",
                },
                {
                    question: "Can I choose extras?",
                    answer:
                        "Yes, you can add cover letter, LinkedIn rewrite, ATS check, and more.",
                },
                {
                    question: "Are templates ATS friendly?",
                    answer:
                        "All templates are optimised for Applicant Tracking Systems.",
                },
            ],
        },

        // 🟣 FINAL CTA
        {
            type: "custom",
            component: "MissionBanner",
            title: "Ready to Boost Your Career?",
            description:
                "Choose your method — manual or AI — and get your professional CV today.",
            image: "image19",
            buttonText: "Start Now",
            buttonLink: "/order/manual",
        },
    ],
};

export default schema;
