export type CountryOption = {
    code: string;
    name: string;
};

const ALL_COUNTRIES: CountryOption[] = [
    { code: "ALB", name: "Albania" },
    { code: "DZA", name: "Algeria" },
    { code: "AND", name: "Andorra" },
    { code: "AGO", name: "Angola" },
    { code: "ATG", name: "Antigua and Barbuda" },
    { code: "ARG", name: "Argentina" },
    { code: "ARM", name: "Armenia" },
    { code: "AUS", name: "Australia" },
    { code: "AUT", name: "Austria" },
    { code: "AZE", name: "Azerbaijan" },
    { code: "BHS", name: "Bahamas" },
    { code: "BHR", name: "Bahrain" },
    { code: "BGD", name: "Bangladesh" },
    { code: "BRB", name: "Barbados" },
    { code: "BEL", name: "Belgium" },
    { code: "BLZ", name: "Belize" },
    { code: "BEN", name: "Benin" },
    { code: "BTN", name: "Bhutan" },
    { code: "BOL", name: "Bolivia" },
    { code: "BIH", name: "Bosnia and Herzegovina" },
    { code: "BWA", name: "Botswana" },
    { code: "BRA", name: "Brazil" },
    { code: "BRN", name: "Brunei" },
    { code: "BGR", name: "Bulgaria" },
    { code: "BFA", name: "Burkina Faso" },
    { code: "BDI", name: "Burundi" },
    { code: "CPV", name: "Cabo Verde" },
    { code: "KHM", name: "Cambodia" },
    { code: "CMR", name: "Cameroon" },
    { code: "CAN", name: "Canada" },
    { code: "TCD", name: "Chad" },
    { code: "CHL", name: "Chile" },
    { code: "CHN", name: "China" },
    { code: "COL", name: "Colombia" },
    { code: "COM", name: "Comoros" },
    { code: "COG", name: "Congo" },
    { code: "CRI", name: "Costa Rica" },
    { code: "CIV", name: "Cote d'Ivoire" },
    { code: "HRV", name: "Croatia" },
    { code: "CYP", name: "Cyprus" },
    { code: "CZE", name: "Czechia" },
    { code: "DNK", name: "Denmark" },
    { code: "DJI", name: "Djibouti" },
    { code: "DMA", name: "Dominica" },
    { code: "DOM", name: "Dominican Republic" },
    { code: "ECU", name: "Ecuador" },
    { code: "EGY", name: "Egypt" },
    { code: "SLV", name: "El Salvador" },
    { code: "GNQ", name: "Equatorial Guinea" },
    { code: "ERI", name: "Eritrea" },
    { code: "EST", name: "Estonia" },
    { code: "SWZ", name: "Eswatini" },
    { code: "ETH", name: "Ethiopia" },
    { code: "FJI", name: "Fiji" },
    { code: "FIN", name: "Finland" },
    { code: "FRA", name: "France" },
    { code: "GAB", name: "Gabon" },
    { code: "GMB", name: "Gambia" },
    { code: "GEO", name: "Georgia" },
    { code: "DEU", name: "Germany" },
    { code: "GHA", name: "Ghana" },
    { code: "GRC", name: "Greece" },
    { code: "GRD", name: "Grenada" },
    { code: "GTM", name: "Guatemala" },
    { code: "GIN", name: "Guinea" },
    { code: "GNB", name: "Guinea-Bissau" },
    { code: "GUY", name: "Guyana" },
    { code: "HND", name: "Honduras" },
    { code: "HUN", name: "Hungary" },
    { code: "ISL", name: "Iceland" },
    { code: "IND", name: "India" },
    { code: "IDN", name: "Indonesia" },
    { code: "IRL", name: "Ireland" },
    { code: "ISR", name: "Israel" },
    { code: "ITA", name: "Italy" },
    { code: "JAM", name: "Jamaica" },
    { code: "JPN", name: "Japan" },
    { code: "JOR", name: "Jordan" },
    { code: "KAZ", name: "Kazakhstan" },
    { code: "KEN", name: "Kenya" },
    { code: "KIR", name: "Kiribati" },
    { code: "KWT", name: "Kuwait" },
    { code: "KGZ", name: "Kyrgyzstan" },
    { code: "LAO", name: "Laos" },
    { code: "LVA", name: "Latvia" },
    { code: "LBN", name: "Lebanon" },
    { code: "LSO", name: "Lesotho" },
    { code: "LBR", name: "Liberia" },
    { code: "LBY", name: "Libya" },
    { code: "LIE", name: "Liechtenstein" },
    { code: "LTU", name: "Lithuania" },
    { code: "LUX", name: "Luxembourg" },
    { code: "MDG", name: "Madagascar" },
    { code: "MWI", name: "Malawi" },
    { code: "MYS", name: "Malaysia" },
    { code: "MDV", name: "Maldives" },
    { code: "MLT", name: "Malta" },
    { code: "MHL", name: "Marshall Islands" },
    { code: "MRT", name: "Mauritania" },
    { code: "MUS", name: "Mauritius" },
    { code: "MEX", name: "Mexico" },
    { code: "FSM", name: "Micronesia" },
    { code: "MDA", name: "Moldova" },
    { code: "MCO", name: "Monaco" },
    { code: "MNG", name: "Mongolia" },
    { code: "MNE", name: "Montenegro" },
    { code: "MAR", name: "Morocco" },
    { code: "MOZ", name: "Mozambique" },
    { code: "NAM", name: "Namibia" },
    { code: "NRU", name: "Nauru" },
    { code: "NPL", name: "Nepal" },
    { code: "NLD", name: "Netherlands" },
    { code: "NZL", name: "New Zealand" },
    { code: "NIC", name: "Nicaragua" },
    { code: "NER", name: "Niger" },
    { code: "NGA", name: "Nigeria" },
    { code: "MKD", name: "North Macedonia" },
    { code: "NOR", name: "Norway" },
    { code: "OMN", name: "Oman" },
    { code: "PAK", name: "Pakistan" },
    { code: "PLW", name: "Palau" },
    { code: "PSE", name: "Palestine" },
    { code: "PAN", name: "Panama" },
    { code: "PNG", name: "Papua New Guinea" },
    { code: "PRY", name: "Paraguay" },
    { code: "PER", name: "Peru" },
    { code: "PHL", name: "Philippines" },
    { code: "POL", name: "Poland" },
    { code: "PRT", name: "Portugal" },
    { code: "QAT", name: "Qatar" },
    { code: "ROU", name: "Romania" },
    { code: "RWA", name: "Rwanda" },
    { code: "KNA", name: "Saint Kitts and Nevis" },
    { code: "LCA", name: "Saint Lucia" },
    { code: "VCT", name: "Saint Vincent and the Grenadines" },
    { code: "WSM", name: "Samoa" },
    { code: "SMR", name: "San Marino" },
    { code: "STP", name: "Sao Tome and Principe" },
    { code: "SAU", name: "Saudi Arabia" },
    { code: "SEN", name: "Senegal" },
    { code: "SRB", name: "Serbia" },
    { code: "SYC", name: "Seychelles" },
    { code: "SLE", name: "Sierra Leone" },
    { code: "SGP", name: "Singapore" },
    { code: "SVK", name: "Slovakia" },
    { code: "SVN", name: "Slovenia" },
    { code: "SLB", name: "Solomon Islands" },
    { code: "ZAF", name: "South Africa" },
    { code: "KOR", name: "South Korea" },
    { code: "ESP", name: "Spain" },
    { code: "LKA", name: "Sri Lanka" },
    { code: "SUR", name: "Suriname" },
    { code: "SWE", name: "Sweden" },
    { code: "CHE", name: "Switzerland" },
    { code: "TJK", name: "Tajikistan" },
    { code: "TZA", name: "Tanzania" },
    { code: "THA", name: "Thailand" },
    { code: "TLS", name: "Timor-Leste" },
    { code: "TGO", name: "Togo" },
    { code: "TON", name: "Tonga" },
    { code: "TTO", name: "Trinidad and Tobago" },
    { code: "TUN", name: "Tunisia" },
    { code: "TUR", name: "Turkey" },
    { code: "TKM", name: "Turkmenistan" },
    { code: "TUV", name: "Tuvalu" },
    { code: "UGA", name: "Uganda" },
    { code: "UKR", name: "Ukraine" },
    { code: "ARE", name: "United Arab Emirates" },
    { code: "GBR", name: "United Kingdom" },
    { code: "USA", name: "United States" },
    { code: "URY", name: "Uruguay" },
    { code: "UZB", name: "Uzbekistan" },
    { code: "VUT", name: "Vanuatu" },
    { code: "VAT", name: "Vatican City" },
    { code: "VNM", name: "Vietnam" },
    { code: "ZMB", name: "Zambia" },
];

export const RESTRICTED_COUNTRY_CODES = new Set([
    "RUS",
    "BLR",
    "IRN",
    "PRK",
    "SYR",
    "YEM",
    "AFG",
    "SDN",
    "SSD",
    "CUB",
    "VEN",
    "ZWE",
    "MMR",
    "MLI",
    "COD",
    "CAF",
    "SOM",
    "IRQ",
    "HTI",
]);

export const ALLOWED_COUNTRIES: CountryOption[] = ALL_COUNTRIES.filter(
    (country) => !RESTRICTED_COUNTRY_CODES.has(country.code)
);

const ALLOWED_COUNTRY_CODES = new Set(ALLOWED_COUNTRIES.map((country) => country.code));

export function isAllowedCountryCode(countryCode: string): boolean {
    return ALLOWED_COUNTRY_CODES.has(countryCode.trim().toUpperCase());
}

export function getCountryNameByCode(countryCode: string): string | null {
    const match = ALLOWED_COUNTRIES.find(
        (country) => country.code === countryCode.trim().toUpperCase()
    );
    return match?.name ?? null;
}
